<?php

/**
 * @file
 * Primary module hooks for quiltme_picsart module.
 */

use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function quiltme_picsart_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  $node = $form_state->getFormObject()->getEntity();
  if ($node->bundle() == "user_submission") {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'quiltme_picsart_custom_user_submission_submit';
      }
    }
  }
}

/**
 * Custom submit function for user submission node bundle.
 */
function quiltme_picsart_custom_user_submission_submit(&$form, FormStateInterface &$form_state) {

  $image_media = Media::load($form_state->getValue('field_original_image')['selection'][0]['target_id']);
  $image_file = File::load($image_media->field_media_image->target_id);
  $image_file_url = \Drupal::request()->getSchemeAndHttpHost() . $image_file->createFileUrl();

  $options = [
    'image_url' => $image_file_url,
    'level' => 'l5',
    'email' => $form_state->getValue('field_user_email')[0]['value'],
    'node' => $form_state->getFormObject()->getEntity(),
  ];

  $random_pattern_numbers = array_rand(range(0, 28), 4);

  $batch = [
    'title' => t('Getting processed images...'),
    'init_message'     => t('Commencing...'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message'    => t('An error occurred during processing'),
    'finished' => 'quiltme_picsart_get_style_transfer_images_callback_finished',
  ];

  foreach ($random_pattern_numbers as $pattern_number) {
    $options['pattern_number'] = sprintf("%02d", $pattern_number);
    $batch['operations'][] = [
      'quiltme_picsart_get_style_transfer_images_callback', [$options],
    ];
  }

  batch_set($batch);

}

/**
 * Saves API generated images to a node.
 */
function quiltme_picsart_get_style_transfer_images_callback($options, &$context) {

  $results = [];

  $picsart = \Drupal::service('quiltme_picsart.connector');
  $node = $options['node'];

  // Should be an absolute URL to the images.
  $pattern_url = "http://dev-4k-quiltme.pantheonsite.io/themes/custom/quiltme/images/patterns/pattern-{$options['pattern_number']}.png";

  $options['reference_image_url'] = $pattern_url;

  $media_id = $picsart->getStyleTransferMediaId($options);

  $node->field_processed_images[] = ['target_id' => $media_id];
  $results[] = $media_id;

  $node->save();

  $context['results'][] = $media_id;
  $context['message'] = t('Created @title', ['@title' => $pattern_url]);

}

/**
 * Batch finished callback.
 */
function quiltme_picsart_get_style_transfer_images_finished_callback($success, $results, $operations) {

  if ($success) {
    $message = \Drupal::translation()->formatPlural(
      count($results),
      'One image processed.', '@count images processed.'
    );
  }
  else {
    $message = t('Finished with an error.');
  }
  \Drupal::messenger()->addStatus($message);
}
